=== sguazt/dcspy-gridpov/examples/conf/gridpov-conf.dtd
<!--
<!DOCTYPE dcs:gridpov-conf [
-->

<!ELEMENT dcs:gridpov-conf (dcs:java,dcs:mygridwrapper?,dcs:mygrid,dcs:povray,dcs:scene)>
<!ATTLIST dcs:gridpov-conf
	xmlns:dcs CDATA #FIXED "http://dcs.di.unipmn.it"
	version (1.0) "1.0"
>

<!ELEMENT dcs:java (dcs:javac-cmd?,dcs:java-cmd?,dcs:java-cp?)> <!-- The Java configuration section -->
<!ELEMENT dcs:javac-cmd (#PCDATA)> <!-- the Java "javac" command path -->
<!ELEMENT dcs:java-cmd (#PCDATA)> <!-- the Java "java" command path -->
<!ELEMENT dcs:java-cp (dcs:java-cp-item*)> <!-- the Java "classpath" options -->
<!ELEMENT dcs:java-cp-item (#PCDATA)> <!-- A Java "classpath" option -->
<!ELEMENT dcs:mygridwrapper (dcs:mygridwrapper-class?)> <!-- The MyGridWrapper configuration section -->
<!ELEMENT dcs:mygridwrapper-class (#PCDATA)> <!-- The MyGridWrapper class name -->
<!ELEMENT dcs:mygrid (dcs:mygrid-cmd,dcs:mygrid-jdf)> <!-- The MyGrid configuration section -->
<!ELEMENT dcs:mygrid-cmd (#PCDATA)> <!-- The MyGrid "mygrid" command path -->
<!ELEMENT dcs:mygrid-jdf (dcs:mygrid-jdf-store-path,dcs:mygrid-jdf-store-method,dcs:mygrid-jdf-tmp-path)> <!-- The MyGrid JDF configuration section -->
<!ELEMENT dcs:mygrid-jdf-store-path (#PCDATA)> <!-- The MyGrid JDF storage path (e.g. $STORAGE) -->
<!ELEMENT dcs:mygrid-jdf-store-method (#PCDATA)> <!-- The MyGrid JDF storage method (put/store) -->
<!ELEMENT dcs:mygrid-jdf-tmp-path (#PCDATA)> <!-- The MyGrid JDF playpen (i.e. temporarily) path (e.g. $PLAYPEN) -->
<!ELEMENT dcs:povray (dcs:povray-cmd,dcs:povray-exec-steps)> <!-- The Povray configuration section -->
<!ELEMENT dcs:povray-cmd (#PCDATA)> <!-- The Povray "povray" command path -->
<!ELEMENT dcs:povray-exec-steps (dcs:povray-exec-step*)> <!-- The number of povray execution steps -->
<!ELEMENT dcs:povray-exec-step (dcs:povray-exec-step-infile,dcs:povray-exec-step-outfile?)> <!-- A step of the povray execution steps -->
<!ELEMENT dcs:povray-exec-step-infile (#PCDATA)> <!-- The input file path of a povray execution step -->
<!ELEMENT dcs:povray-exec-step-outfile (#PCDATA)> <!-- The output file path of a povray execution step -->
<!ELEMENT dcs:scene (dcs:scene-files,dcs:scene-width?,dcs:scene-height?,dcs:scene-bounding?,dcs:scene-quality?,dcs:scene-antialias?,dcs:scene-alpha?,dcs:scene-lightbuf?,dcs:scene-vistabuf?,dcs:scene-blocksize?,dcs:scene-imagefmt?)> <!-- The Scene configuration section -->
<!ATTLIST dcs:scene
	label CDATA #IMPLIED
>
<!ELEMENT dcs:scene-width EMPTY>
<!ATTLIST dcs:scene-width
	value CDATA "320"
>
<!ELEMENT dcs:scene-height EMPTY>
<!ATTLIST dcs:scene-height
	value CDATA "200"
>
<!ELEMENT dcs:scene-bounding EMPTY>
<!ATTLIST dcs:scene-bounding
	threshold CDATA #REQUIRED
>
<!ELEMENT dcs:scene-quality EMPTY>
<!ATTLIST dcs:scene-quality
	value (0|1|2|3|4|5|6|7|8|9) #REQUIRED
>
<!ELEMENT dcs:scene-antialias EMPTY>
<!ATTLIST dcs:scene-antialias
	threshold CDATA #IMPLIED
	method (1|2) #IMPLIED
	jitter CDATA #IMPLIED
	depth CDATA #IMPLIED
>
<!ELEMENT dcs:scene-alpha EMPTY>
<!ELEMENT dcs:scene-lightbuf EMPTY>
<!ELEMENT dcs:scene-vistabuf EMPTY>
<!ELEMENT dcs:scene-blocksize EMPTY>
<!ATTLIST dcs:scene-blocksize
	value CDATA "64"
>
<!ELEMENT dcs:scene-imagefmt EMPTY>
<!ATTLIST dcs:scene-imagefmt
	type (C|N|P|T) "N"
	bits (5|6|7|8|9|10|11|12|13|14|15|16) "8"
>
<!ELEMENT dcs:scene-files (dcs:scene-file*)>
<!ELEMENT dcs:scene-file (#PCDATA)>

<!--
]>
-->

=== sguazt/dcspy-gridpov/examples/conf/dmwave.xml
<?xml version="1.0"?>

<!DOCTYPE dcs:gridpov-conf SYSTEM "gridpov-conf.dtd">

<dcs:gridpov-conf xmlns:dcs="http://dcs.di.unipmn.it" version="1.0">
	<!-- MyGrid section -->
	<dcs:mygrid>
		<dcs:mygrid-cmd>/usr/local/opt/OurGrid/mygrid/bin/mygrid</dcs:mygrid-cmd>

		<dcs:mygrid-jdf>
			<dcs:mygrid-jdf-store-path>$STORAGE</dcs:mygrid-jdf-store-path>
			<dcs:mygrid-jdf-store-method>store</dcs:mygrid-jdf-store-method>
			<dcs:mygrid-jdf-tmp-path>$PLAYPEN</dcs:mygrid-jdf-tmp-path>
		</dcs:mygrid-jdf>
	</dcs:mygrid>

	<!-- POV-Ray section -->
	<dcs:povray>
		<dcs:povray-cmd>/usr/local/bin/povray</dcs:povray-cmd>
		<dcs:povray-exec-steps>
			<dcs:povray-exec-step>
				<dcs:povray-exec-step-infile>dmwave.pov</dcs:povray-exec-step-infile>
				<dcs:povray-exec-step-outfile>dmwave.png</dcs:povray-exec-step-outfile>
			</dcs:povray-exec-step>
		</dcs:povray-exec-steps>
	</dcs:povray>

	<!-- Scene configurazione -->
	<dcs:scene label="dmwave">
		<dcs:scene-files>
			<dcs:scene-file>test/scenes/dmwave/boat.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/dmwave/box.png</dcs:scene-file>
			<dcs:scene-file>test/scenes/dmwave/dmwave.pov</dcs:scene-file>
			<dcs:scene-file>test/scenes/dmwave/grid.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/dmwave/spot.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/dmwave/wavelet.inc</dcs:scene-file>
		</dcs:scene-files>
		<dcs:scene-width value="320"/>
		<dcs:scene-height value="240"/>
<!--
		<dcs:scene-bounding threshold="3"/>
		<dcs:scene-quality value="3"/>
		<dcs:scene-antialias threshold="3" method="1" jitter="0.0" depth="0"/>
		<dcs:scene-alpha/>
		<dcs:scene-lightbuf/>
		<dcs:scene-vistabuf/>
-->
		<dcs:scene-antialias threshold="3"/>
		<dcs:scene-blocksize value="50"/>
		<dcs:scene-imagefmt type="N" bits="8"/>
	</dcs:scene>
</dcs:gridpov-conf>

=== sguazt/dcspy-gridpov/examples/conf/teapot.xml
<?xml version="1.0"?>

<!DOCTYPE dcs:gridpov-conf SYSTEM "gridpov-conf.dtd">

<dcs:gridpov-conf xmlns:dcs="http://dcs.di.unipmn.it" version="1.0">
	<!-- MyGrid section -->
	<dcs:mygrid>
		<dcs:mygrid-cmd>/usr/local/opt/OurGrid/mygrid/bin/mygrid</dcs:mygrid-cmd>

		<dcs:mygrid-jdf>
			<dcs:mygrid-jdf-store-path>$STORAGE</dcs:mygrid-jdf-store-path>
			<dcs:mygrid-jdf-store-method>store</dcs:mygrid-jdf-store-method>
			<dcs:mygrid-jdf-tmp-path>$PLAYPEN</dcs:mygrid-jdf-tmp-path>
		</dcs:mygrid-jdf>
	</dcs:mygrid>

	<!-- POV-Ray section -->
	<dcs:povray>
		<dcs:povray-cmd>/usr/local/bin/povray</dcs:povray-cmd>
		<dcs:povray-exec-steps>
			<dcs:povray-exec-step>
				<dcs:povray-exec-step-infile>teapot.pov</dcs:povray-exec-step-infile>
				<dcs:povray-exec-step-outfile>teapot.png</dcs:povray-exec-step-outfile>
			</dcs:povray-exec-step>
		</dcs:povray-exec-steps>
	</dcs:povray>

	<!-- Scene configurazione -->
	<dcs:scene label="teapot">
		<dcs:scene-files>
			<dcs:scene-file>test/scenes/teapot/teapot.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/teapot/teapot.pov</dcs:scene-file>
		</dcs:scene-files>
		<dcs:scene-width value="800"/>
		<dcs:scene-height value="600"/>
<!--
		<dcs:scene-bounding threshold="3"/>
		<dcs:scene-quality value="3"/>
		<dcs:scene-antialias threshold="3" method="1" jitter="0.0" depth="0"/>
		<dcs:scene-alpha/>
		<dcs:scene-lightbuf/>
		<dcs:scene-vistabuf/>
-->
		<dcs:scene-antialias threshold="3"/>
<!--
		<dcs:scene-blocksize value="64"/>
-->
		<dcs:scene-blocksize value="256"/>
		<dcs:scene-imagefmt type="N" bits="8"/>
	</dcs:scene>
</dcs:gridpov-conf>

=== sguazt/dcspy-gridpov/examples/conf/dissolution.xml
<?xml version="1.0"?>

<!DOCTYPE dcs:gridpov-conf SYSTEM "gridpov-conf.dtd">

<dcs:gridpov-conf xmlns:dcs="http://dcs.di.unipmn.it" version="1.0">
	<!-- MyGrid section -->
	<dcs:mygrid>
		<dcs:mygrid-cmd>/usr/local/opt/OurGrid/mygrid/bin/mygrid</dcs:mygrid-cmd>

		<dcs:mygrid-jdf>
			<dcs:mygrid-jdf-store-path>$STORAGE</dcs:mygrid-jdf-store-path>
			<dcs:mygrid-jdf-store-method>store</dcs:mygrid-jdf-store-method>
			<dcs:mygrid-jdf-tmp-path>$PLAYPEN</dcs:mygrid-jdf-tmp-path>
		</dcs:mygrid-jdf>
	</dcs:mygrid>

	<!-- POV-Ray section -->
	<dcs:povray>
		<dcs:povray-cmd>/usr/local/bin/povray</dcs:povray-cmd>
		<dcs:povray-libs>/usr/local/share/povray/include</dcs:povray-libs>
		<dcs:povray-libs>/usr/local/share/povray/include/LightsysIV</dcs:povray-libs>
		<dcs:povray-exec-steps>
			<dcs:povray-exec-step>
				<dcs:povray-exec-step-infile>dissolution.pov</dcs:povray-exec-step-infile>
				<dcs:povray-exec-step-outfile>dissolution.png</dcs:povray-exec-step-outfile>
			</dcs:povray-exec-step>
		</dcs:povray-exec-steps>
	</dcs:povray>

	<!-- Scene configurazione -->
	<dcs:scene label="dissolution">
		<dcs:scene-files>
			<dcs:scene-file>test/scenes/dissolution/cell.inc</dcs:scene-file>
<!-- LightsysIV file (already available on grid machines)
			<dcs:scene-file>test/scenes/dissolution/CIE.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/dissolution/CIE_precalculation.pov</dcs:scene-file>
			<dcs:scene-file>test/scenes/dissolution/CIE_Skylight.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/dissolution/CIE_tools.inc</dcs:scene-file>
-->
			<dcs:scene-file>test/scenes/dissolution/dissolution.pov</dcs:scene-file>
			<dcs:scene-file>test/scenes/dissolution/espd_cie_standard.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/dissolution/espd_lightsys.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/dissolution/espd_sun.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/dissolution/fbodies.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/dissolution/lights.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/dissolution/lightsys_colors.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/dissolution/lightsys_constants.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/dissolution/lightsys.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/dissolution/linemapn.png</dcs:scene-file>
			<dcs:scene-file>test/scenes/dissolution/lspd_elements.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/dissolution/manipulator.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/dissolution/metal1.png</dcs:scene-file>
			<dcs:scene-file>test/scenes/dissolution/rspd_aster.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/dissolution/rspd_jvp.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/dissolution/rspd_lunar.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/dissolution/rspd_pantone_coated.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/dissolution/rspd_pantone_matte.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/dissolution/rspd_pantone_uncoated.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/dissolution/scratch.jpg</dcs:scene-file>
		</dcs:scene-files>
		<dcs:scene-width value="800"/>
		<dcs:scene-height value="600"/>
<!--
		<dcs:scene-bounding threshold="3"/>
		<dcs:scene-quality value="3"/>
		<dcs:scene-antialias threshold="3" method="1" jitter="0.0" depth="0"/>
		<dcs:scene-alpha/>
		<dcs:scene-lightbuf/>
		<dcs:scene-vistabuf/>
-->
		<dcs:scene-antialias threshold="3"/>
<!--
		<dcs:scene-blocksize value="64"/>
-->
		<dcs:scene-blocksize value="256"/>
		<dcs:scene-imagefmt type="N" bits="8"/>
	</dcs:scene>
</dcs:gridpov-conf>

=== sguazt/dcspy-gridpov/examples/conf/scifi.xml
<?xml version="1.0"?>

<!DOCTYPE dcs:gridpov-conf SYSTEM "gridpov-conf.dtd">

<dcs:gridpov-conf xmlns:dcs="http://dcs.di.unipmn.it" version="1.0">
	<!-- MyGrid section -->
	<dcs:mygrid>
		<dcs:mygrid-cmd>/usr/local/opt/OurGrid/mygrid/bin/mygrid</dcs:mygrid-cmd>

		<dcs:mygrid-jdf>
			<dcs:mygrid-jdf-store-path>$STORAGE</dcs:mygrid-jdf-store-path>
			<dcs:mygrid-jdf-store-method>store</dcs:mygrid-jdf-store-method>
			<dcs:mygrid-jdf-tmp-path>$PLAYPEN</dcs:mygrid-jdf-tmp-path>
		</dcs:mygrid-jdf>
	</dcs:mygrid>

	<!-- POV-Ray section -->
	<dcs:povray>
		<dcs:povray-cmd>/usr/local/bin/povray</dcs:povray-cmd>
		<dcs:povray-libs>/usr/local/share/povray/include</dcs:povray-libs>
		<dcs:povray-libs>/usr/local/share/povray/include/LightsysIV</dcs:povray-libs>
		<dcs:povray-exec-steps>
			<dcs:povray-exec-step>
				<dcs:povray-exec-step-infile>scifi.pov</dcs:povray-exec-step-infile>
				<dcs:povray-exec-step-outfile>scifi.png</dcs:povray-exec-step-outfile>
			</dcs:povray-exec-step>
		</dcs:povray-exec-steps>
	</dcs:povray>

	<!-- Scene configurazione -->
	<dcs:scene label="scifi">
		<dcs:scene-files>
			<dcs:scene-file>test/scenes/scifi/scifi.pov</dcs:scene-file>
			<dcs:scene-file>test/scenes/scifi/build03_o.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/scifi/build04_o.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/scifi/build05_o.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/scifi/build06_o.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/scifi/build07_o.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/scifi/bushead_o.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/scifi/bus_o.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/scifi/bustail_o.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/scifi/car1d_o.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/scifi/car4_o.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/scifi/car5_o.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/scifi/car6_o.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/scifi/car7_o.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/scifi/concrete_03.jpg</dcs:scene-file>
			<dcs:scene-file>test/scenes/scifi/concrete_04.jpg</dcs:scene-file>
			<dcs:scene-file>test/scenes/scifi/concrete_05.jpg</dcs:scene-file>
			<dcs:scene-file>test/scenes/scifi/csign33.jpg</dcs:scene-file>
			<dcs:scene-file>test/scenes/scifi/rust_01.jpg</dcs:scene-file>
			<dcs:scene-file>test/scenes/scifi/rust_03.jpg</dcs:scene-file>
			<dcs:scene-file>test/scenes/scifi/shiphull.jpg</dcs:scene-file>
			<dcs:scene-file>test/scenes/scifi/truck1_o.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/scifi/truck2_o.inc</dcs:scene-file>
		</dcs:scene-files>
		<dcs:scene-width value="800"/>
		<dcs:scene-height value="600"/>
<!--
		<dcs:scene-bounding threshold="3"/>
		<dcs:scene-quality value="3"/>
		<dcs:scene-antialias threshold="3" method="1" jitter="0.0" depth="0"/>
		<dcs:scene-alpha/>
		<dcs:scene-lightbuf/>
		<dcs:scene-vistabuf/>
-->
		<dcs:scene-antialias threshold="3"/>
		<dcs:scene-blocksize value="64"/>
		<dcs:scene-imagefmt type="N" bits="8"/>
	</dcs:scene>
</dcs:gridpov-conf>

=== sguazt/dcspy-gridpov/examples/conf/minicooper.xml
<?xml version="1.0"?>

<!DOCTYPE dcs:gridpov-conf SYSTEM "gridpov-conf.dtd">

<dcs:gridpov-conf xmlns:dcs="http://dcs.di.unipmn.it" version="1.0">
	<!-- MyGrid section -->
	<dcs:mygrid>
		<dcs:mygrid-cmd>/usr/local/opt/OurGrid/mygrid/bin/mygrid</dcs:mygrid-cmd>

		<dcs:mygrid-jdf>
			<dcs:mygrid-jdf-store-path>$STORAGE</dcs:mygrid-jdf-store-path>
			<dcs:mygrid-jdf-store-method>store</dcs:mygrid-jdf-store-method>
			<dcs:mygrid-jdf-tmp-path>$PLAYPEN</dcs:mygrid-jdf-tmp-path>
		</dcs:mygrid-jdf>
	</dcs:mygrid>

	<!-- POV-Ray section -->
	<dcs:povray>
		<dcs:povray-cmd>/usr/local/bin/povray</dcs:povray-cmd>
		<dcs:povray-libs>/usr/local/share/povray/include</dcs:povray-libs>
		<dcs:povray-libs>/usr/local/share/povray/include/LightsysIV</dcs:povray-libs>
		<dcs:povray-exec-steps>
			<dcs:povray-exec-step>
				<dcs:povray-exec-step-infile>minicooper.pov</dcs:povray-exec-step-infile>
				<dcs:povray-exec-step-outfile>minicooper.png</dcs:povray-exec-step-outfile>
			</dcs:povray-exec-step>
		</dcs:povray-exec-steps>
	</dcs:povray>

	<!-- Scene configurazione -->
	<dcs:scene label="minicooper">
		<dcs:scene-files>
			<dcs:scene-file>test/scenes/minicooper/minicooper.pov</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_border_o.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_bricks1_bump.jpg</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_bricks1.jpg</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_bricks1_o.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_bricks2_bump.jpg</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_bricks2.jpg</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_colside1_bump.jpg</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_colside1.jpg</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_colside1_o.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_column1b_bump.jpg</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_column1b.jpg</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_column1_bump.jpg</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_column1c_bump.jpg</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_column1c.jpg</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_column1d_bump.jpg</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_column1d.jpg</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_column1door_bump.jpg</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_column1door.jpg</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_column1door_o.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_column1.jpg</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_column1_o.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_column2b_bump.jpg</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_column2b.jpg</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_column2_bump.jpg</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_column2c_bump.jpg</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_column2c.jpg</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_column2.jpg</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_column2_o.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_concrete2.jpg</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_concrete_bump.jpg</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_corner1a_bump.jpg</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_corner1a.jpg</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_corner1a_o.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_corner1b_bump.jpg</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_corner1b.jpg</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_corner1b_o.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_corner1_bump.jpg</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_corner1.jpg</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_corner1_o.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_corner2_bump.jpg</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_corner2.jpg</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_corner2_o.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_cover_bmp.jpg</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_cover.jpg</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_cover_o.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_curtain_o.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_dframe_o.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_door1.jpg</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_door1_o.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_door2d_bump.jpg</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_door2d.jpg</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_door2.jpg</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_door2_o.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_doortop_bump.jpg</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_doortop.jpg</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_doortop_o.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_front1a_bump.jpg</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_front1a.jpg</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_front1a_o.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_front1_bump.jpg</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_front1.jpg</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_front1_o.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_glass1_o.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_glass2_o.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_glass_o.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_ledge2_bump.jpg</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_ledge2.jpg</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_ledge2_o.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_ledge2w_bump.jpg</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_ledge2w.jpg</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_ledge2w_o.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_mdoorledge_bump.jpg</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_mdoorledge.jpg</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_mdoorledge_o.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_mdoor_o.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_mdoortop_o.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_number_o.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_road2.jpg</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_road_hf3.jpg</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_sidewalk_o.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_window1d_o.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_window1_o.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_window2_o.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_window.jpg</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/bd_windows_o.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/car_paint2.jpg</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/headlight_bmp.jpg</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/headlight.jpg</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/lplate.jpg</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/mini_emblem.jpg</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/mini_mesh_o.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/minicooper/parkingsign.jpg</dcs:scene-file>
		</dcs:scene-files>
		<dcs:scene-width value="600"/>
		<dcs:scene-height value="600"/>
<!--
		<dcs:scene-bounding threshold="3"/>
		<dcs:scene-quality value="3"/>
		<dcs:scene-antialias threshold="3" method="1" jitter="0.0" depth="0"/>
		<dcs:scene-alpha/>
		<dcs:scene-lightbuf/>
		<dcs:scene-vistabuf/>
-->
		<dcs:scene-antialias threshold="3"/>
		<dcs:scene-blocksize value="64"/>
		<dcs:scene-imagefmt type="N" bits="8"/>
	</dcs:scene>
</dcs:gridpov-conf>

=== sguazt/dcspy-gridpov/examples/conf/glass.xml
<?xml version="1.0"?>

<!DOCTYPE dcs:gridpov-conf SYSTEM "gridpov-conf.dtd">

<dcs:gridpov-conf xmlns:dcs="http://dcs.di.unipmn.it" version="1.0">
	<!-- MyGrid section -->
	<dcs:mygrid>
		<dcs:mygrid-cmd>/usr/local/opt/OurGrid/mygrid/bin/mygrid</dcs:mygrid-cmd>

		<dcs:mygrid-jdf>
			<dcs:mygrid-jdf-store-path>$STORAGE</dcs:mygrid-jdf-store-path>
			<dcs:mygrid-jdf-store-method>store</dcs:mygrid-jdf-store-method>
			<dcs:mygrid-jdf-tmp-path>$PLAYPEN</dcs:mygrid-jdf-tmp-path>
		</dcs:mygrid-jdf>
	</dcs:mygrid>

	<!-- POV-Ray section -->
	<dcs:povray>
		<dcs:povray-cmd>/usr/local/bin/povray</dcs:povray-cmd>
		<dcs:povray-libs>/usr/local/share/povray/include</dcs:povray-libs>
		<dcs:povray-libs>/usr/local/share/povray/include/LightsysIV</dcs:povray-libs>
		<dcs:povray-exec-steps>
			<dcs:povray-exec-step>
				<dcs:povray-exec-step-infile>glass.pov</dcs:povray-exec-step-infile>
				<dcs:povray-exec-step-outfile>glass.png</dcs:povray-exec-step-outfile>
			</dcs:povray-exec-step>
		</dcs:povray-exec-steps>
	</dcs:povray>

	<!-- Scene configurazione -->
	<dcs:scene label="glass">
		<dcs:scene-files>
			<dcs:scene-file>test/scenes/glass/glass.pov</dcs:scene-file>
			<dcs:scene-file>test/scenes/glass/ashtray_o.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/glass/dice_o.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/glass/glass1_liquid_bottom_o.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/glass/glass1_liquid_full_o.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/glass/glass1_o.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/glass/glass2_liquid_bottom_o.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/glass/glass2_liquid_full_o.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/glass/glass2_o.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/glass/glass3_liquid_bottom_o.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/glass/glass3_liquid_full_o.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/glass/glass3_o.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/glass/glass4_liquid_bottom_o.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/glass/glass4_liquid_full_o.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/glass/glass4_o.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/glass/icecubes_o.inc</dcs:scene-file>
			<dcs:scene-file>test/scenes/glass/pitcher_o.inc</dcs:scene-file>
		</dcs:scene-files>
		<dcs:scene-width value="800"/>
		<dcs:scene-height value="600"/>
<!--
		<dcs:scene-bounding threshold="3"/>
		<dcs:scene-quality value="3"/>
		<dcs:scene-antialias threshold="3" method="1" jitter="0.0" depth="0"/>
		<dcs:scene-alpha/>
		<dcs:scene-lightbuf/>
		<dcs:scene-vistabuf/>
-->
		<dcs:scene-antialias threshold="3"/>
		<dcs:scene-blocksize value="64"/>
		<dcs:scene-imagefmt type="N" bits="8"/>
	</dcs:scene>
</dcs:gridpov-conf>
